name: build-runtime
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Fetching Build Tools
        working-directory: /home/runner/work/
        run: git clone https://github.com/mirkobrombin/runtimezilla.git
      
      - name: Install dependencies
        working-directory: /home/runner/work/runtimezilla
        run: |
          sudo dpkg --add-architecture i386
          sudo apt -y install software-properties-common
          sudo add-apt-repository ppa:cybermax-dexter/vkd3d -y
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport -y
          sudo apt-get -qq update
          sudo apt install -y aptitude
          sudo python3 -m pip install -r requirements.txt 
      
      - name: Launch build.py
        working-directory: /home/runner/work/runtimezilla
        run: |
          python3 runtimezilla --recipe ../runtime-tests/runtime-tests/recipe.yml --output runtime-build
          ls runtime-build/lib32
          
      - name: Upload runtime-build.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: runtime-build.tar.gz
          path: /home/runner/work/runtimezilla/runtime-build.tar.gz
          
      - name: Upload log.txt
        uses: actions/upload-artifact@v2
        with:
          name: log.txt
          path: /home/runner/work/runtimezilla/log.txt
